### ISSUE TITLE
documentation needs to be updated to reflect the need to set mongodb config, else there are error

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.repex.at#1]
(virtualenv)RandomDisorder:re_package shantenu$ RADICAL_PILOT_VERBOSE=debug python radical_re_namd.py --input='config/input.json' --resource='config/xsede.json'
2014:05:19 11:40:03 radical.pilot.MainProcess: [INFO    ] radical.pilot version: 0.12

---
-                     Replica Exchange with NAMD                    *
  *********************************************************************
  Traceback (most recent call last):
  File "radical_re_namd.py", line 361, in <module>
    session, pilot_manager, pilot_object = re.launch_pilot(r_config)
  File "radical_re_namd.py", line 282, in launch_pilot
    session = radical.pilot.Session(database_url=self.dburl)
  File "/Users/shantenu/virtualenv/lib/python2.7/site-packages/radical/pilot/session.py", line 138, in **init**
    db_name=database_name)
  File "/Users/shantenu/virtualenv/lib/python2.7/site-packages/radical/pilot/db/database.py", line 80, in new
    dbs = Session(db_url, db_name)
  File "/Users/shantenu/virtualenv/lib/python2.7/site-packages/radical/pilot/db/database.py", line 59, in **init**
    self._client = MongoClient(db_url)
  File "/Users/shantenu/virtualenv/lib/python2.7/site-packages/pymongo/mongo_client.py", line 366, in __init__
    raise ConnectionFailure(str(e))
  pymongo.errors.ConnectionFailure: [Errno 8] nodename nor servname provided, or not known

**Comment by shantenujha** [comment]
Can this be made consistent like the other tools where the user does not have to worry about setting up mongodb urls please? 

I think it is not good to expose a very-early/primitive user of EnsembleMD to details of MongoDB. Will be sure to scare them away (90% of them will not even know what it is!)

**Comment by antonst** [comment]
I agree! and I had MongoDB url defined in input.json before, but on Friday Vivek while testing my code told me that Ole told him that we must not expose MongoDB url in our code, so I changed it.
