### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.repex.at#18]
I cannot run RepEx: I re-checked out everything and rebuilt them.  The error message is below:

Taisung

sh  launcher_amber_2d.sh

/usr/people/taisung/myenv/lib/python2.7/site-packages/pkg_resources.py:1045: UserWarning: /usr/people/taisung/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).

  warnings.warn(msg, UserWarning)

Traceback (most recent call last):

  File "launch_simulation_pattern_b_amber_2d.py", line 13, in <module>

```
import radical.pilot
```

  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/radical.pilot-0.23-py2.7.egg/radical/pilot/**init**.py", line 25, in <module>

```
from url import Url
```

  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/radical.pilot-0.23-py2.7.egg/radical/pilot/url.py", line 14, in <module>

```
from saga import Url as sagaURL
```

  File "/usr/people/taisung/myenv/lib/python2.7/site-packages/saga_python-0.26-py2.7.egg/saga/**init**.py", line 46, in <module>

```
version, version_detail, version_branch = ru.get_version ([root, pwd])
```

ValueError: too many values to unpack

**Comment by jhonsen** [comment]
Is there a solution to this? I'm having the same problem

**Comment by andre-merzky** [comment]
Hi, 

it seems you are mixing release and development versions somewhere, or devel and master branches.

In general, the following three packages should come either all from devel branches, or all from master/releases/pypi:  radical.pilot, radical.utils, saga-python.

**Comment by jhonsen** [comment]
got it thank you
