### ISSUE TITLE
key error "shell"

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.repex.at#46]
I see this stack:

```
2015-10-18 00:09:11,945: radical.saga.pty    : MainProcess                     : MainThread     : DEBUG   : copy done: ['mput', 'Uploading', '/tmp/ve/local/lib/python2.7/site-packages/Rep', 'sftp>']
2015-10-18 00:09:14,947: radical.repex       : MainProcess                     : MainThread     : INFO    : Performing cycle: 1
2015-10-18 00:09:14,947: radical.repex       : MainProcess                     : MainThread     : INFO    : Creating 16 replica tasks for MD-step. cycle 1
Traceback (most recent call last):
  File "/tmp/ve/bin/repex-amber", line 4, in <module>
    __import__('pkg_resources').run_script('RepEx===0.2-devel-antons-2c827d7-', 'repex-amber')
  File "/tmp/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/tmp/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/tmp/ve/lib/python2.7/site-packages/RepEx-0.2_devel_antons_2c827d7_-py2.7.egg/EGG-INFO/scripts/repex-amber", line 58, in <module>
    pilot_kernel.run_simulation( replicas, pilot_object, session, md_kernel )
  File "/tmp/ve/local/lib/python2.7/site-packages/RepEx-0.2_devel_antons_2c827d7_-py2.7.egg/pilot_kernels/pilot_kernel_pattern_s.py", line 181, in run_simulation
    compute_replica = md_kernel.prepare_replica_for_md(r, self.sd_shared_list)
  File "/tmp/ve/local/lib/python2.7/site-packages/RepEx-0.2_devel_antons_2c827d7_-py2.7.egg/amber_kernels_tex/kernel_pattern_s_tex.py", line 296, in prepare_replica_for_md
    if KERNELS[self.resource]["shell"] == "bourne":
KeyError: 'shell'
```

when running

```
repex-amber --input='t_remd_ala10.json' --rconfig='<resource>.json'
```

towards archer.   FWIW, the error seemed not to abort the script (but I assume it should...)

**Comment by antonst** [comment]
Thanks Andre :-) Fixed now in devel-antons
